

```{r}
library(package = "tidyverse")
library(package = "readxl")

```


```{r}
xlfile = "./LOCA2_Inventory_Validation.xlsx"
```

```{r}
pr_sheet = read_excel(path = xlfile, sheet="pr")
tx_sheet = read_excel(path = xlfile, sheet="tasmax")
tn_sheet = read_excel(path = xlfile, sheet="tasmin")
dt_sheet = read_excel(path = xlfile, sheet="DTR")

remove(xlfile)


inventory = rbind(pr_sheet,  tx_sheet)
inventory = rbind(inventory, tn_sheet)
inventory = rbind(inventory, dt_sheet)



remove(pr_sheet,tx_sheet,tn_sheet,dt_sheet)

inventory = pivot_longer(data          = inventory,
                         cols          = "DJF-RMSE":"SON-BIAS",
                         names_to      = c("Season", "Stat"),
                         names_pattern = "(.*)-(.*)",
                         values_to     = "value")

inventory = inventory %>% 
  filter(Member!="ENSAVG") %>%
  select("Model", "Member", "Var", "Season", "Stat", "value")

inventory$Stat    = factor(x      = inventory$Stat,
                          levels = c("BIAS","RMSE","Both"))

inventory$Season = factor(x      = inventory$Season,
                          levels = c("DJF","MAM","JJA","SON","Annual"))


inventory$Var    = factor(x      = inventory$Var,
                          levels = c("pr","tasmax","tasmin","DTR", "All"))

inventory$Model  = factor(x = inventory$Model)
inventory$Member = factor(x = inventory$Member)

colnames(inventory)

inventory$Rank = NA

#inventory = inventory %>% filter(Var != "DTR")

```


```{r}
inv_stat = inventory %>%
  group_by(Model, Member, Var, Season) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Stat = "Both",
         Rank = rank(value))  %>%
  arrange(value) %>%
  ungroup() 

inv_season = inventory %>%
  group_by(Model, Member, Var, Stat) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Season = "Annual",
         Rank   = rank(value))   %>%
  arrange(value) %>%
  ungroup()

inv_var = inventory %>%
  group_by(Model, Member, Season, Stat) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Var = "All",
         Rank   = rank(value))   %>%
  arrange(value) %>%
  ungroup() 

  
```




```{r}


inv_var_season = inventory %>%
  group_by(Model, Member, Stat) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Var    = "All",
         Season = "Annual",
         Rank   = rank(value))  %>%
  arrange(value) %>%
  ungroup()

inv_season_stat = inventory %>%
  group_by(Model, Member, Var) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Season = "Annual",
         Stat   = "Both",
         Rank   = rank(value))   %>%
  arrange(value) %>%
  ungroup()

inv_var_stat = inventory %>%
  group_by(Model, Member, Season) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Var     = "All",
         Stat    = "Both",
         Rank    = rank(value))  %>%
  ungroup()



inv_var_season_stat = inventory %>%
  group_by(Model,Member) %>%
  summarize(value = sqrt(sum(value^2))) %>%
  mutate(Var    = "All",
         Season = "Annual",
         Stat   = "Both",
         Rank   = rank(value))   %>%
  arrange(value) %>%
  ungroup()


```

```{r}

inventory_1_errors = inv_var_season_stat %>% 
  group_by(Model) %>%
  filter(Rank == 1 )  %>%
  arrange(value) %>%
  ungroup() 
  
  
inventory_2_errors = inv_var_season_stat %>% 
  group_by(Model) %>%
  filter(Rank == 2 ) %>%
  arrange(value) %>%
  ungroup() 
  
inventory_3_errors = inv_var_season_stat %>% 
  group_by(Model) %>%
  filter(Rank == 3 )  %>%
  arrange(value) %>%
  ungroup() 

inventory_E1_errors = inv_var_season_stat %>% 
  filter(Member == "r1i1p1f1",
         Rank > 2)  %>%
  arrange(value) %>%
  ungroup() 


inventory_E1_errorsXX = inv_var_season_stat %>% 
  filter(Member == "r1i1p1f1")  %>%
  arrange(value) %>%
  ungroup() 

```


```{r}
  
inventory = rbind(inventory, inv_season)
inventory = rbind(inventory, inv_stat)
inventory = rbind(inventory, inv_var)
inventory = rbind(inventory, inv_season_stat)
inventory = rbind(inventory, inv_var_season)
inventory = rbind(inventory, inv_var_stat)
inventory = rbind(inventory, inv_var_season_stat)

inventory$Stat    = factor(x     = inventory$Stat,
                          levels = c("BIAS", "RMSE", "Both"))

inventory$Season = factor(x      = inventory$Season,
                          levels = c("DJF", "MAM", "JJA", "SON", "Annual"))


inventory$Var    = factor(x      = inventory$Var,
                          levels = c("pr", "tasmax", "tasmin", "DTR", "All"))

inventory = inventory %>% arange(values)
```







```{r}

inventory2 = pivot_wider(data = inventory %>% select(-Rank),
                        names_from = "Stat")

remove(inv_season)
remove(inv_stat)
remove(inv_var)
remove(inv_season_stat)
remove(inv_var_season)
remove(inv_var_stat)
remove(inv_var_season_stat)

write_csv(x = inventory_1_errors,  file = "./LOCA2_R1_Full_Summary_Errors.csv")
write_csv(x = inventory_2_errors,  file = "./LOCA2_R2_Full_Summary_Errors.csv")
write_csv(x = inventory_3_errors,  file = "./LOCA2_R3_Full_Summary_Errors.csv")
write_csv(x = inventory_E1_errors, file = "./LOCA2_E1_Full_Summary_Errors.csv")
write_csv(x = inventory,           file = "./LOCA2_All_Errors.csv")

```


```{r}



```


```{r}
temp  = inventory2 %>% 
  filter(Season != "Annual" & Var != "All")


temp2 = inventory_1_errors   %>% filter(Season != "Annual" & Var != "All")


ggplot(data = temp) +
  aes(x=BIAS,
      y=RMSE,
      color=Var) +
  theme_bw()+
  facet_wrap(vars(Season))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "All Variables and Seasons, No Aggregation") +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 1)+ 
  xlim(min(c(temp$BIAS)),max(c(temp$BIAS)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  geom_point(size = 0.75)


ggplot(data = temp2) +
  aes(x=BIAS,
      y=RMSE,
      color=Model,
      shape=Var) +
  theme_bw()+
  theme(legend.text = element_text(size = 8)) +
  theme(legend.spacing.x = unit(0, 'cm')) +
  theme(legend.spacing.y = unit(0, 'cm')) +
  facet_wrap(vars(Season))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "All Variables and Seasons, No Aggregation") +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) +
  coord_fixed(ratio = 1)+ 
  xlim(min(c(temp$BIAS)),max(c(temp$BIAS)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  geom_point(data=temp, alpha=0.25, size=0.75)+
  geom_point()


remove(temp,temp2)



```



```{r}

temp = inventory2             %>% filter(Season == "Annual" & Var !="All" )
temp2 = inventory_1_errors %>% filter(Season == "Annual" & Var != "All")

ggplot(data = temp) +
  aes(x=BIAS,
      y=RMSE,shape=Var,
      color=Var) +
  theme_bw()+
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) + 
  coord_fixed(ratio = 1)+ 
  xlim(0,max(c(temp$BIAS,temp$RMSE)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "Aggregated across Seasons") +
  geom_point()

ggplot(data = temp2) +
  aes(x=BIAS,
      y=RMSE,shape=Var,
      color=Model) +
  theme_bw()+
  theme(legend.text = element_text(size = 8)) +
  theme(legend.spacing.x = unit(0, 'cm')) +
  theme(legend.spacing.y = unit(0, 'cm')) +
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) + 
  coord_fixed(ratio = 1)+ 
  xlim(0,max(c(temp$BIAS,temp$RMSE)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "Aggregated across Seasons") +
  geom_point(data=temp, alpha=0.25, size=0.75) +
  geom_point(data=temp2)

remove(temp,temp2)
```

```{r}

temp2  = inventory2           %>% filter(Season =="Annual" & Var == "All")

temp = inventory_1_errors %>% filter(Season =="Annual" & Var == "All")

ggplot(data = temp) +
  aes(x=BIAS,
      y=RMSE,
      color=Model) +
  theme_bw()+
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) + 
  coord_fixed(ratio = 1)+ 
  xlim(0,max(c(temp$BIAS,temp$RMSE)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "Aggregated across Seasons & Variables") +  
  geom_point()

ggplot(data = temp2) +
  aes(x=BIAS,
      y=RMSE,
      color=Model) +
  theme_bw()+
  geom_hline(yintercept = 0) + 
  geom_vline(xintercept = 0) + 
  coord_fixed(ratio = 1)+ 
  xlim(0,max(c(temp$BIAS,temp$RMSE)))+
  ylim(0,max(c(temp$BIAS,temp$RMSE)))+
  ggtitle(label    = "LOCA2 CONUS Validation",
          subtitle = "Aggregated across Seasons & Variables") +  
  geom_point(data=temp, alpha=0.25, size=0.75)+
  geom_point()

remove(temp,temp2)

```
